### ISSUE TITLE
Need the ability to store mmstats results in a database connection

### ISSUE THREAD

**Issue by psbanka** [schmichael/mmstats#29]
For hosted services like Heroku, getting access to the filesystem for the running process for viewing stats is not easy. This would be far simpler if stats could simply be logged to a database connection, say providing mmstats with a postgresql connection URL?

**Comment by schmichael** [comment]
mmstats is focused on being a lightweight way to expose metrics - using any sort of IO breaks that "lightweight" goal (other than the current mmap'd file where all of the IO outside of setup & teardown is handled by the kernel).

So I see 3 options:
1. Spin up mmash from within your process at startup time with some code like:

``` python
from multiprocessing import Process

from mmstats import mmash

p = Process(target=mmash.main)
p.start() # Starts mmash (an http server exposing stats) in a subprocess

# Start your app normally
myapp.run() # for example
```

This gives you a web interface to _poll_ and insert the metrics (perhaps aggregated) into a database.

2. Write your own mmstats/reader.py/MmStatsReader subclass to read your app's metrics and write them to your database. If you go this route I'd love to include your code (or a subset of it) as an example in mmstats' repo. A configurable version of it could be included as a first class tool like pollstats/slurpstats/mmash outright.

3. Use a metrics solution with builtin database support like graphite. This is the _push_ solution to the previous solutions pull. It has more of an impact on your app (network IO) and requires an external dependency (the database), but for many use cases these are perfectly acceptable.
