### ISSUE TITLE
Need an orphaned mmstat cleaning script

### ISSUE THREAD

**Issue by schmichael** [schmichael/mmstats#6]
Python's atexit handler isn't foolproof and in production it's common for orphaned stale mmstat files to hang around and confuse readers.

A simple cleaning script would check the sys.pid stat's status and remove the file if the PID doesn't exist.

**Comment by robotadam** [comment]
+1. Could re-use this for socketconsole.

**Comment by schmichael** [comment]
Added in 6290a6e54b8151a6febab3209eac36a15c8e22f7 and released in 0.4
